# Generated by Django 4.1.13 on 2024-03-04 18:36

from django.db import migrations


def update_cart_items(apps, schema_editor):
    CartItem = apps.get_model('product', 'CartItem')
    Product = apps.get_model('product', 'Product')

    # Iterate over existing CartItem instances
    for cart_item in CartItem.objects.all():
        # Check if there's an existing CartItem with the same product
        existing_item = CartItem.objects.filter(
            product=cart_item.product).exclude(pk=cart_item.pk).first()
        if existing_item:
            # If exists, update the quantity by adding the new quantity
            existing_item.quantity += cart_item.quantity
            existing_item.save()
            # Delete the current instance as it has been merged with the existing one
            cart_item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cartitem_created_date_cartitem_updated_date_and_more'),
    ]

    operations = [
        migrations.RunPython(update_cart_items),
    ]
